# Generated by Django 4.1 on 2022-10-09 15:39

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('my_account', '0008_invoice_dateend_invoice_datestart_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='dateStart',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='endDate',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 9, 11, 39, 37, 533023)),
        ),
        migrations.AlterField(
            model_name='postinvoice',
            name='dateStart',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='date',
            field=models.DateField(default=datetime.datetime(2022, 10, 9, 15, 39, 37, 534020, tzinfo=datetime.timezone.utc)),
        ),
    ]
