# Generated by Django 4.1 on 2022-10-09 22:54

import datetime
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('my_account', '0009_alter_invoice_datestart_alter_invoice_enddate_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtraService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=150)),
                ('price', models.IntegerField(blank=True)),
                ('monthly', models.IntegerField(blank=True, default=1)),
                ('summary', models.TextField(blank=True, null=True)),
                ('desc', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AlterField(
            model_name='invoice',
            name='endDate',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 9, 18, 54, 33, 619694)),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.CreateModel(
            name='ExtraInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('name', models.CharField(blank=True, max_length=200)),
                ('subTotal', models.IntegerField(blank=True, default=0)),
                ('total', models.IntegerField(blank=True, default=0)),
                ('subTotalMonthly', models.IntegerField(blank=True, default=0)),
                ('totalMonthly', models.IntegerField(blank=True, default=0)),
                ('sendingForPayment', models.BooleanField(default=False)),
                ('priceID', models.CharField(blank=True, max_length=150, null=True)),
                ('paid', models.BooleanField(default=False)),
                ('dateStart', models.DateField(default=django.utils.timezone.now)),
                ('dateEnd', models.DateField(blank=True, null=True)),
                ('tax', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='my_account.tax')),
            ],
        ),
        migrations.AddField(
            model_name='useraccount',
            name='extraInvoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='my_account.extrainvoice'),
        ),
        migrations.AddField(
            model_name='useraccount',
            name='extraService',
            field=models.ManyToManyField(blank=True, related_name='extraServices', to='my_account.extraservice'),
        ),
    ]
