# Generated by Django 4.1 on 2022-10-10 03:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_account', '0010_extraservice_alter_invoice_enddate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extrainvoice',
            name='dateStart',
            field=models.DateField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='dateStart',
            field=models.DateField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='endDate',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 9, 23, 8, 28, 524931)),
        ),
        migrations.AlterField(
            model_name='postinvoice',
            name='dateStart',
            field=models.DateField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='date',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
