# Generated by Django 4.1 on 2022-10-11 15:01

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('my_account', '0012_useraccount_extrasessionid_alter_invoice_enddate'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricecatelog',
            name='subCategory',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='endDate',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 11, 11, 1, 46, 155911)),
        ),
        migrations.AlterField(
            model_name='price',
            name='priceCatelog',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='price', to='my_account.pricecatelog'),
        ),
    ]
