# Generated by Django 4.1 on 2022-10-11 15:18

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('my_account', '0013_pricecatelog_subcategory_alter_invoice_enddate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='extraservice',
            name='priceCatelog',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='extraService', to='my_account.pricecatelog'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='endDate',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 11, 11, 18, 16, 528912)),
        ),
        migrations.AlterField(
            model_name='product',
            name='priceCatelog',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='product', to='my_account.pricecatelog'),
        ),
    ]
