# Generated by Django 4.1 on 2022-10-11 16:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_account', '0014_extraservice_pricecatelog_alter_invoice_enddate_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='postservice',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='price',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='service',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='extraservice',
            name='priceCatelog',
        ),
        migrations.AlterField(
            model_name='invoice',
            name='endDate',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 11, 12, 52, 40, 336239)),
        ),
        migrations.RemoveField(
            model_name='product',
            name='priceCatelog',
        ),
        migrations.AddField(
            model_name='extraservice',
            name='priceCatelog',
            field=models.ManyToManyField(blank=True, related_name='extraService', to='my_account.pricecatelog'),
        ),
        migrations.RemoveField(
            model_name='postservice',
            name='priceCatelog',
        ),
        migrations.RemoveField(
            model_name='price',
            name='priceCatelog',
        ),
        migrations.AddField(
            model_name='product',
            name='priceCatelog',
            field=models.ManyToManyField(blank=True, related_name='product', to='my_account.pricecatelog'),
        ),
        migrations.RemoveField(
            model_name='service',
            name='priceCatelog',
        ),
        migrations.AddField(
            model_name='postservice',
            name='priceCatelog',
            field=models.ManyToManyField(blank=True, related_name='postService', to='my_account.pricecatelog'),
        ),
        migrations.AddField(
            model_name='price',
            name='priceCatelog',
            field=models.ManyToManyField(blank=True, related_name='price', to='my_account.pricecatelog'),
        ),
        migrations.AddField(
            model_name='service',
            name='priceCatelog',
            field=models.ManyToManyField(blank=True, related_name='service', to='my_account.pricecatelog'),
        ),
    ]
