# Generated by Django 4.1 on 2022-10-12 15:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_account', '0015_alter_postservice_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extrainvoice',
            name='dateEnd',
            field=models.DateField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='dateEnd',
            field=models.DateField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='endDate',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='postinvoice',
            name='dateEnd',
            field=models.DateField(blank=True, default=datetime.datetime.now),
        ),
    ]
