# Generated by Django 4.1 on 2022-10-17 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_account', '0016_alter_extrainvoice_dateend_alter_invoice_dateend_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='extrainvoice',
            name='numPayment',
            field=models.IntegerField(blank=True, default=60),
        ),
        migrations.AddField(
            model_name='postinvoice',
            name='numPayment',
            field=models.IntegerField(blank=True, default=60),
        ),
    ]
