# Generated by Django 4.1 on 2022-10-17 19:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('my_account', '0017_extrainvoice_numpayment_postinvoice_numpayment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='options',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='my_account.option'),
        ),
    ]
