# Generated by Django 4.1 on 2022-10-19 02:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_account', '0018_alter_useraccount_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extrainvoice',
            name='dateEnd',
            field=models.DateField(blank=True, default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='dateEnd',
            field=models.DateField(blank=True, default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='postinvoice',
            name='dateEnd',
            field=models.DateField(blank=True, default=datetime.date.today),
        ),
    ]
