# Generated by Django 4.1 on 2022-10-28 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_account', '0020_alter_tax_country_alter_tax_subregion'),
    ]

    operations = [
        migrations.AddField(
            model_name='price',
            name='summary',
            field=models.TextField(blank=True),
        ),
    ]
