# Generated by Django 4.1 on 2022-11-03 16:18

import datetime
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('my_account', '0021_price_summary'),
    ]

    operations = [
        migrations.CreateModel(
            name='Calculator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Q', models.CharField(blank=True, max_length=300, null=True)),
                ('yesno', models.BooleanField(default=True)),
                ('ans', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(default='no', max_length=300), default=list, size=None)),
                ('dateNow', models.DateTimeField(default=datetime.datetime.now)),
                ('date', models.DateField(auto_now_add=True)),
                ('extra_services', models.ManyToManyField(blank=True, related_name='calc_extra_services', to='my_account.service')),
                ('post_services', models.ManyToManyField(blank=True, related_name='calc_post_services', to='my_account.postservice')),
                ('priceCatelog', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='calculator', to='my_account.pricecatelog')),
                ('services', models.ManyToManyField(blank=True, related_name='calc_services', to='my_account.service')),
            ],
        ),
    ]
