# Generated by Django 4.1 on 2022-11-04 14:38

import django.contrib.postgres.fields
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('my_account', '0022_calculator'),
    ]

    operations = [
        migrations.CreateModel(
            name='TempSavedCalculator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('postServiceIdArr', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(default=0), default=list, size=None)),
                ('total', models.IntegerField(default=0)),
                ('serviceIdArr', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(default=0), default=list, size=None)),
            ],
        ),
    ]
