# Generated by Django 4.1 on 2022-11-04 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_account', '0023_tempsavedcalculator'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='calcUUID',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
