# Generated by Django 4.1 on 2022-11-05 01:29

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_account', '0024_useraccount_calcuuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='tempsavedcalculator',
            name='additionalCharArr',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=100), default=list, size=None),
        ),
    ]
