# Generated by Django 4.1 on 2022-11-05 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_account', '0026_jobs'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobs',
            old_name='name',
            new_name='userId',
        ),
    ]
