# Generated by Django 4.1 on 2022-11-07 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_account', '0027_rename_name_jobs_userid'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='DNS',
            field=models.CharField(blank=True, max_length=75, null=True),
        ),
        migrations.AddField(
            model_name='useraccount',
            name='website',
            field=models.CharField(blank=True, max_length=75, null=True),
        ),
    ]
