# Generated by Django 4.1 on 2022-11-07 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_account', '0029_useraccount_industry'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='co',
            field=models.CharField(blank=True, max_length=75, null=True),
        ),
    ]
