# Generated by Django 4.1 on 2022-11-07 19:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('my_account', '0030_useraccount_co'),
    ]

    operations = [
        migrations.CreateModel(
            name='SitePreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50)),
                ('site', models.CharField(blank=True, max_length=100)),
                ('q1', models.CharField(blank=True, max_length=100)),
                ('ans1', models.TextField(blank=True)),
                ('q2', models.CharField(blank=True, max_length=100)),
                ('ans2', models.TextField(blank=True)),
                ('q3', models.CharField(blank=True, max_length=100)),
                ('ans3', models.TextField(blank=True)),
            ],
        ),
        migrations.AddField(
            model_name='useraccount',
            name='sitePreference',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='my_account.sitepreference'),
        ),
    ]
