# Generated by Django 4.1 on 2022-11-08 18:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_account', '0031_sitepreference_useraccount_sitepreference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extrainvoice',
            name='dateEnd',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='extrainvoice',
            name='dateStart',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='dateEnd',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='dateStart',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='postinvoice',
            name='dateEnd',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='postinvoice',
            name='dateStart',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
