# Generated by Django 4.1 on 2022-11-21 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_account', '0033_postservice_services_alter_postservice_pricecatelog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postservice',
            name='priceCatelog',
            field=models.ManyToManyField(blank=True, related_name='postService', to='my_account.pricecatelog'),
        ),
    ]
