# Generated by Django 4.1 on 2022-11-21 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_account', '0034_alter_postservice_pricecatelog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postservice',
            name='services',
            field=models.ManyToManyField(blank=True, related_name='dependantServices', to='my_account.service'),
        ),
    ]
