# Generated by Django 4.1 on 2022-11-24 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_account', '0035_alter_postservice_services'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='calculator',
            options={'ordering': ['id']},
        ),
        migrations.RemoveField(
            model_name='useraccount',
            name='DNS',
        ),
        migrations.AddField(
            model_name='useraccount',
            name='CDN',
            field=models.CharField(blank=True, default='False', max_length=75),
        ),
    ]
