# Generated by Django 4.1 on 2022-11-27 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_account', '0036_alter_calculator_options_remove_useraccount_dns_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='newWebsite',
            field=models.CharField(blank=True, max_length=75, null=True),
        ),
        migrations.AddField(
            model_name='useraccount',
            name='publishComplete',
            field=models.BooleanField(default=False),
        ),
    ]
