# Generated by Django 4.1 on 2022-11-28 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_account', '0040_creditinvoice_prodsservs_creditinvoice_prodsservs_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='creditinvoice',
            old_name='paid',
            new_name='hasCredit',
        ),
        migrations.RemoveField(
            model_name='creditinvoice',
            name='priceID',
        ),
    ]
