# Generated by Django 4.1 on 2022-12-09 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_account', '0041_rename_paid_creditinvoice_hascredit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='extraservice',
            name='image',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='postservice',
            name='image',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='extraServices',
            field=models.ManyToManyField(blank=True, to='my_account.extraservice'),
        ),
        migrations.AddField(
            model_name='product',
            name='postServices',
            field=models.ManyToManyField(blank=True, to='my_account.postservice'),
        ),
        migrations.AddField(
            model_name='product',
            name='services',
            field=models.ManyToManyField(blank=True, to='my_account.service'),
        ),
        migrations.AddField(
            model_name='service',
            name='image',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
