# Generated by Django 4.1 on 2022-12-09 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_account', '0042_extraservice_image_postservice_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='type',
            field=models.CharField(choices=[('pageDesign', 'pageDesign'), ('subDesign', 'subDesign'), ('pageTemplate', 'pageTemplate'), ('subTemplate', 'subTemplate')], default='pageDesign', max_length=50),
        ),
    ]
