# Generated by Django 4.1 on 2022-12-09 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_account', '0043_product_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('aboutPage', 'aboutPage'), ('contactPage', 'contactPage'), ('footer', 'footer'), ('navBar', 'navBar'), ('detailPage', 'detailPage'), ('blogPage', 'blogPage'), ('frontPage', 'frontPage'), ('articlePage', 'articlePage'), ('sidebar', 'sidebar')], default='frontPage', max_length=50),
        ),
    ]
