# Generated by Django 4.1 on 2022-12-10 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_account', '0044_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('aboutPage', 'aboutPage'), ('contactPage', 'contactPage'), ('footer', 'footer'), ('navBar', 'navBar'), ('detailPage', 'detailPage'), ('blogPage', 'blogPage'), ('frontPage', 'frontPage'), ('articlePage', 'articlePage'), ('sidebar', 'sidebar'), ('signin', 'signin'), ('registration', 'registration'), ('checkout', 'checkout')], default='frontPage', max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='type',
            field=models.CharField(choices=[('pageDesign', 'pageDesign'), ('subDesign', 'subDesign'), ('pageTemplate', 'pageTemplate'), ('subTemplate', 'subTemplate'), ('nonDesign', 'nonDesign'), ('subNonDesign', 'subNonDesign')], default='pageDesign', max_length=50),
        ),
        migrations.CreateModel(
            name='ServiceDependancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(blank=True, max_length=70, null=True)),
                ('compare', models.BooleanField(default=False)),
                ('extraServices', models.ManyToManyField(blank=True, to='my_account.extraservice')),
                ('postServices', models.ManyToManyField(blank=True, to='my_account.postservice')),
                ('products', models.ManyToManyField(blank=True, to='my_account.product')),
                ('services', models.ManyToManyField(blank=True, to='my_account.service')),
            ],
        ),
    ]
