# Generated by Django 4.1 on 2022-12-12 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_account', '0046_servicedependancy_des_alter_product_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='servicedependancy',
            old_name='des',
            new_name='desc',
        ),
    ]
