# Generated by Django 4.1 on 2022-12-17 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_account', '0049_product_savings_alter_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='update',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='updated',
            field=models.BooleanField(default=False),
        ),
    ]
