# Generated by Django 4.1 on 2022-12-17 12:23

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_account', '0050_product_update_product_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='tempsavedcalculator',
            name='CDN',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='tempsavedcalculator',
            name='co',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='tempsavedcalculator',
            name='highTech',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tempsavedcalculator',
            name='industry',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='tempsavedcalculator',
            name='productIdArr',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(default=0), default=list, size=None),
        ),
        migrations.AddField(
            model_name='tempsavedcalculator',
            name='website',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
