# Generated by Django 4.1 on 2022-12-17 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_account', '0051_tempsavedcalculator_cdn_tempsavedcalculator_co_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='savings',
            field=models.IntegerField(blank=True, default=1),
        ),
    ]
