# Generated by Django 4.1 on 2022-12-18 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_account', '0052_invoice_savings'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='city',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
