# Generated by Django 4.1 on 2022-12-19 15:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_account', '0053_useraccount_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extrainvoice',
            name='dateEnd',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
