# Generated by Django 4.1 on 2022-12-20 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_account', '0054_alter_extrainvoice_dateend'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='image',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
