# Generated by Django 4.1 on 2022-12-20 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_account', '0055_package_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='savings',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
