# Generated by Django 4.1 on 2022-12-23 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_account', '0056_package_savings'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditinvoice',
            name='update',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='creditinvoice',
            name='yesUpdated',
            field=models.BooleanField(default=False),
        ),
    ]
