# Generated by Django 4.1 on 2023-03-21 17:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('my_account', '0058_alter_package_options_alter_product_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='frontCover',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='calculator',
            name='dateNow',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='creditinvoice',
            name='dateStart',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='extrainvoice',
            name='dateEnd',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='extrainvoice',
            name='dateStart',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='dateEnd',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='dateStart',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='postinvoice',
            name='dateEnd',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='postinvoice',
            name='dateStart',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('aboutPage', 'aboutPage'), ('contactPage', 'contactPage'), ('footer', 'footer'), ('navBar', 'navBar'), ('detailPage', 'detailPage'), ('blogPage', 'blogPage'), ('frontPage', 'frontPage'), ('articlePage', 'articlePage'), ('sidebar', 'sidebar'), ('signin', 'signin'), ('registration', 'registration'), ('checkout', 'checkout'), ('userAccount', 'userAccount'), ('customFrontPage', 'customFrontPage'), ('changeEmailPage', 'changeEmailPage'), ('changePasswordPage', 'changePasswordPage'), ('internetSales', 'internetSales'), ('SEO', 'SEO'), ('fileSystem', 'fileSystem'), ('video', 'video')], default='frontPage', max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='type',
            field=models.CharField(choices=[('pageDesign', 'pageDesign'), ('subDesign', 'subDesign'), ('pageTemplate', 'pageTemplate'), ('subTemplate', 'subTemplate'), ('nonDesign', 'nonDesign'), ('subNonDesign', 'subNonDesign'), ('video', 'video')], default='pageDesign', max_length=50),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
