# Generated by Django 4.1 on 2022-11-06 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminHome', '0002_suminvoice'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtraServiceTaskTracker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=75, null=True)),
                ('user_id', models.IntegerField(blank=True, null=True)),
                ('Id', models.IntegerField(default=0)),
                ('task', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='PostServiceTaskTracker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=75, null=True)),
                ('user_id', models.IntegerField(blank=True, null=True)),
                ('Id', models.IntegerField(default=0)),
                ('task', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ServiceTaskTracker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=75, null=True)),
                ('user_id', models.IntegerField(blank=True, null=True)),
                ('Id', models.IntegerField(default=0)),
                ('task', models.BooleanField(default=False)),
            ],
        ),
    ]
