# Generated by Django 4.1 on 2022-10-13 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminHome', '0002_suminvoice'),
    ]

    operations = [
        migrations.AddField(
            model_name='suminvoice',
            name='allSubMonthly',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='suminvoice',
            name='allSubTotal',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
