# Generated by Django 4.1 on 2022-10-13 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminHome', '0003_suminvoice_allsubmonthly_suminvoice_allsubtotal'),
    ]

    operations = [
        migrations.AddField(
            model_name='suminvoice',
            name='fedTax',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='suminvoice',
            name='provtax',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
