# Generated by Django 4.1 on 2022-11-03 00:32

import datetime
import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminHome', '0004_suminvoice_fedtax_suminvoice_provtax'),
    ]

    operations = [
        migrations.AddField(
            model_name='rates',
            name='name',
            field=models.CharField(blank=True, max_length=75, null=True),
        ),
        migrations.AddField(
            model_name='suminvoice',
            name='allPaidInvoice',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=70), blank=True, default=list, size=None),
        ),
        migrations.AlterField(
            model_name='suminvoice',
            name='allDateEnd',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.DateField(default=datetime.datetime.now), blank=True, default=list, size=None),
        ),
        migrations.AlterField(
            model_name='suminvoice',
            name='allPriceID',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=250, null=True), blank=True, default=list, size=None),
        ),
    ]
