# Generated by Django 4.1 on 2022-11-22 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminHome', '0005_tasktracker'),
    ]

    operations = [
        migrations.AddField(
            model_name='extraservicetasktracker',
            name='username',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='postservicetasktracker',
            name='username',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='servicetasktracker',
            name='username',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
