# Generated by Django 4.1 on 2022-11-03 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminHome', '0005_rates_name_suminvoice_allpaidinvoice_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='suminvoice',
            name='allPaidInvoice',
        ),
    ]
