# Generated by Django 4.1 on 2022-11-22 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminHome', '0006_extraservicetasktracker_username_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='producttasktracker',
            name='username',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
