# Generated by Django 4.1 on 2022-11-03 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminHome', '0006_remove_suminvoice_allpaidinvoice'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SumInvoice',
        ),
    ]
