# Generated by Django 4.1 on 2022-12-20 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminHome', '0008_rates_years'),
    ]

    operations = [
        migrations.CreateModel(
            name='UpDateItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updatePackages', models.BooleanField(default=False)),
                ('packagesUpdated', models.BooleanField(default=False)),
            ],
        ),
    ]
