# Generated by Django 4.1 on 2022-12-22 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminHome', '0009_updateitems'),
    ]

    operations = [
        migrations.RenameField(
            model_name='updateitems',
            old_name='packagesUpdated',
            new_name='Updated',
        ),
        migrations.RenameField(
            model_name='updateitems',
            old_name='updatePackages',
            new_name='update',
        ),
        migrations.AddField(
            model_name='updateitems',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
