# Generated by Django 4.1 on 2022-12-22 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminHome', '0010_rename_packagesupdated_updateitems_updated_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='producttasktracker',
            name='subTasks',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
