# Generated by Django 4.1 on 2022-12-24 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminHome', '0011_producttasktracker_subtasks'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='extraservicetasktracker',
            options={'ordering': ['-user_id', 'username']},
        ),
        migrations.AlterModelOptions(
            name='postservicetasktracker',
            options={'ordering': ['-user_id', 'username']},
        ),
        migrations.AlterModelOptions(
            name='producttasktracker',
            options={'ordering': ['-user_id', 'username']},
        ),
        migrations.AlterModelOptions(
            name='servicetasktracker',
            options={'ordering': ['-user_id', 'username']},
        ),
    ]
