# Generated by Django 4.1 on 2022-08-17 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_service_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='section',
            field=models.CharField(blank=True, choices=[('allServices', 'allServices'), ('supplemental', 'supplemental'), ('works', 'works'), ('advert', 'advert')], max_length=200),
        ),
        migrations.AddField(
            model_name='service',
            name='subSection',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
