# Generated by Django 4.1 on 2022-08-18 13:58

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_service_section'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='service',
            managers=[
                ('getCat', django.db.models.manager.Manager()),
            ],
        ),
    ]
