# Generated by Django 4.1 on 2022-08-18 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_service_managers'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('cell', models.CharField(blank=True, max_length=100)),
                ('CoName', models.CharField(blank=True, max_length=200)),
                ('site', models.CharField(blank=True, max_length=200)),
                ('content', models.TextField(blank=True)),
            ],
        ),
        migrations.AlterModelManagers(
            name='service',
            managers=[
            ],
        ),
    ]
