# Generated by Django 4.1 on 2022-08-18 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_quote_alter_service_managers'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='promotion',
            field=models.BooleanField(default=False),
        ),
    ]
