# Generated by Django 4.1 on 2022-08-18 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_quote_promotion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quote',
            old_name='CoName',
            new_name='coName',
        ),
        migrations.RenameField(
            model_name='quote',
            old_name='name',
            new_name='coSite',
        ),
        migrations.RenameField(
            model_name='quote',
            old_name='site',
            new_name='fullName',
        ),
    ]
