# Generated by Django 4.1 on 2022-08-19 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_rename_coname_quote_coname_rename_name_quote_cosite_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='section',
            field=models.CharField(choices=[('contact', 'contact'), ('about', 'about'), ('home', 'home'), ('article', 'article'), ('bio', 'bio'), ('main', 'main'), ('footer', 'footer')], default='main', max_length=200),
        ),
    ]
