# Generated by Django 4.1 on 2022-08-19 12:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_category_section'),
    ]

    operations = [
        migrations.CreateModel(
            name='FAQS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(blank=True, max_length=200)),
                ('answer', models.CharField(blank=True, choices=[('allServices', 'allServices'), ('supplemental', 'supplemental'), ('works', 'works'), ('advert', 'advert'), ('main', 'main')], max_length=200)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='catFooter', to='api.category')),
            ],
        ),
    ]
