# Generated by Django 4.1 on 2022-08-20 12:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_faqs_answer'),
    ]

    operations = [
        migrations.CreateModel(
            name='WordSnippets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100)),
                ('sectionTitle', models.CharField(blank=True, max_length=100)),
                ('content', models.TextField(blank=True)),
                ('webImage', models.CharField(blank=True, max_length=250)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='catWordSnippet', to='api.category')),
            ],
        ),
    ]
