# Generated by Django 4.1 on 2022-08-20 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_wordsnippets'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='WordSnippets',
            new_name='WordSnippet',
        ),
    ]
