# Generated by Django 4.1 on 2022-08-20 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_rename_wordsnippets_wordsnippet'),
    ]

    operations = [
        migrations.AddField(
            model_name='wordsnippet',
            name='subSectionTitle',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
