# Generated by Django 4.1 on 2022-09-13 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_region'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='region',
            options={'ordering': ('country', 'provState')},
        ),
        migrations.AlterUniqueTogether(
            name='region',
            unique_together={('country', 'provState')},
        ),
    ]
