# Generated by Django 4.1 on 2022-09-15 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_alter_region_options_alter_region_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='Miscelaneous',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page', models.CharField(blank=True, max_length=40, null=True)),
                ('pageCount', models.IntegerField(default=0, null=True)),
            ],
        ),
    ]
