# Generated by Django 4.1 on 2022-09-15 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_miscelaneous'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='summary',
            field=models.TextField(null=True),
        ),
    ]
