# Generated by Django 4.1 on 2022-09-20 19:47

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_service_summary'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneralInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=75, null=True)),
                ('address', models.CharField(max_length=200, null=True)),
                ('cell', models.IntegerField(blank=True)),
                ('siteArray', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200, null=True), default=list, size=None)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categoryGeneralInfo', to='api.category')),
            ],
        ),
    ]
