# Generated by Django 4.1 on 2022-09-20 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_alter_generalinfo_cell'),
    ]

    operations = [
        migrations.AddField(
            model_name='generalinfo',
            name='country',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='generalinfo',
            name='extra',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='generalinfo',
            name='provState',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
