# Generated by Django 4.1 on 2022-09-20 21:35

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_generalinfo_country_generalinfo_extra_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generalinfo',
            name='siteArray',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.JSONField(), default=list, size=None),
        ),
    ]
