# Generated by Django 4.1 on 2022-09-21 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_sponsor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='section',
            field=models.CharField(choices=[('contact', 'contact'), ('about', 'about'), ('home', 'home'), ('article', 'article'), ('bio', 'bio'), ('main', 'main'), ('footer', 'footer'), ('GeneralInfo', 'GeneralInfo'), ('sponsor', 'sponsor')], default='main', max_length=200),
        ),
    ]
