# Generated by Django 4.1 on 2022-09-22 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_alter_category_section_imagefield'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sponsor',
            name='jsonArray',
        ),
        migrations.AddField(
            model_name='sponsor',
            name='logo',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='sponsor',
            name='site',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
