# Generated by Django 4.1 on 2022-09-22 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_remove_sponsor_jsonarray_sponsor_logo_sponsor_site'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagefield',
            name='image',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
