# Generated by Django 4.1 on 2022-09-22 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_alter_imagefield_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sponsor',
            name='logo',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='sponsor',
            name='site',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
