# Generated by Django 4.1 on 2022-10-06 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0033_generalinfo_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='generalinfo',
            name='postal',
            field=models.CharField(default='L4C-1K8', max_length=50, null=True),
        ),
    ]
