# Generated by Django 4.1 on 2022-10-12 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0034_generalinfo_postal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='section',
            field=models.CharField(blank=True, choices=[('allServices', 'allServices'), ('supplemental', 'supplemental'), ('works', 'works'), ('advert', 'advert'), ('main', 'main'), ('general', 'general'), ('restriction', 'restriction'), ('warning', 'warning')], max_length=200),
        ),
    ]
