# Generated by Django 4.1 on 2022-10-31 19:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0035_alter_service_section'),
    ]

    operations = [
        migrations.CreateModel(
            name='PageFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=75)),
                ('email', models.CharField(blank=True, max_length=100)),
                ('page', models.CharField(blank=True, max_length=50)),
                ('comment', models.TextField(blank=True)),
                ('rating', models.IntegerField(blank=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pageFeedback', to='api.category')),
            ],
        ),
    ]
