# Generated by Django 4.1 on 2022-11-02 20:22

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0037_alter_category_section'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='section',
            field=models.CharField(choices=[('contact', 'contact'), ('about', 'about'), ('home', 'home'), ('article', 'article'), ('bio', 'bio'), ('main', 'main'), ('footer', 'footer'), ('GeneralInfo', 'GeneralInfo'), ('sponsor', 'sponsor'), ('designs', 'designs'), ('policy', 'policy'), ('feedback', 'feedback'), ('calculator', 'calculator')], default='main', max_length=200),
        ),
        migrations.CreateModel(
            name='Calculator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Q', models.CharField(blank=True, max_length=300, null=True)),
                ('yesno', models.BooleanField(default=True)),
                ('ans', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(default='no', max_length=300), default=list, size=None)),
                ('date', models.DateField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calculator', to='api.category')),
            ],
        ),
    ]
