# Generated by Django 4.1 on 2022-11-03 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0038_alter_category_section_calculator'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Calculator',
        ),
    ]
