# Generated by Django 4.1 on 2022-11-03 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0039_delete_calculator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='section',
            field=models.CharField(choices=[('contact', 'contact'), ('about', 'about'), ('home', 'home'), ('article', 'article'), ('bio', 'bio'), ('main', 'main'), ('footer', 'footer'), ('GeneralInfo', 'GeneralInfo'), ('sponsor', 'sponsor'), ('designs', 'designs'), ('policy', 'policy'), ('feedback', 'feedback')], default='main', max_length=200),
        ),
    ]
