# Generated by Django 4.1 on 2022-11-19 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0040_alter_category_section'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagefeedback',
            name='average',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
