# Generated by Django 4.1 on 2022-11-20 14:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0042_alter_pagefeedback_average'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteMap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loc', models.CharField(blank=True, max_length=50, null=True)),
                ('changefreq', models.CharField(blank=True, max_length=50, null=True)),
                ('priority', models.IntegerField(default=10)),
                ('lastmod', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
    ]
