# Generated by Django 4.1 on 2022-11-20 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0043_sitemap'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitemap',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
