# Generated by Django 4.1 on 2022-11-28 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0044_sitemap_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='FAQYes',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='quote',
            name='answer',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='quote',
            name='emailSent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='quote',
            name='sendThemEmail',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='quote',
            name='sendToFAQ',
            field=models.BooleanField(default=False),
        ),
    ]
