# Generated by Django 4.1 on 2022-12-03 09:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0050_miscelaneous_datehit'),
    ]

    operations = [
        migrations.AddField(
            model_name='miscelaneous',
            name='avg',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
        migrations.AddField(
            model_name='miscelaneous',
            name='firstDate',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
