# Generated by Django 4.1 on 2022-12-07 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0052_request_ans_request_sendemail_request_sendtofaqs'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='emailSent',
            field=models.BooleanField(default=False),
        ),
    ]
