# Generated by Django 4.1 on 2022-12-07 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0053_request_emailsent'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='FAQS_sent',
            field=models.BooleanField(default=False),
        ),
    ]
