# Generated by Django 4.1 on 2022-09-29 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogPost', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sectionblog',
            name='content1',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sectionblog',
            name='content2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sectionblog',
            name='mainImage',
            field=models.CharField(blank=True, default='', max_length=175, null=True),
        ),
        migrations.AddField(
            model_name='sectionblog',
            name='subSection',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='sectionblog',
            name='subSection1',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='sectionblog',
            name='subSection2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='titleblog',
            name='mainImage',
            field=models.CharField(blank=True, default='', max_length=175, null=True),
        ),
    ]
