# Generated by Django 4.1 on 2022-09-29 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogPost', '0002_sectionblog_content1_sectionblog_content2_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sectionblog',
            old_name='mainImage',
            new_name='sectionImage',
        ),
    ]
