# Generated by Django 4.1 on 2022-09-29 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogPost', '0003_rename_mainimage_sectionblog_sectionimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='titleblog',
            name='show',
            field=models.BooleanField(default=False),
        ),
    ]
