# Generated by Django 4.1 on 2022-09-29 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogPost', '0004_titleblog_show'),
    ]

    operations = [
        migrations.AddField(
            model_name='titleblog',
            name='imageMain',
            field=models.FileField(blank=True, default='', null=True, upload_to='C:\\Users\\garya\\projects\\NewMaster\\serverSide\\media'),
        ),
    ]
