# Generated by Django 4.1 on 2022-09-29 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogPost', '0006_alter_titleblog_imagemain'),
    ]

    operations = [
        migrations.AlterField(
            model_name='titleblog',
            name='imageMain',
            field=models.FileField(blank=True, default='', null=True, upload_to='blog'),
        ),
    ]
