# Generated by Django 4.1 on 2022-09-29 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogPost', '0007_alter_titleblog_imagemain'),
    ]

    operations = [
        migrations.AddField(
            model_name='sectionblog',
            name='imagesection',
            field=models.FileField(blank=True, default='', null=True, upload_to='blog'),
        ),
    ]
