# Generated by Django 4.1 on 2022-09-29 23:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogPost', '0008_sectionblog_imagesection'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sectionblog',
            old_name='imagesection',
            new_name='imageSection',
        ),
    ]
