# Generated by Django 4.1 on 2022-09-30 13:23

import ckeditor.fields
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blogPost', '0009_rename_imagesection_sectionblog_imagesection'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleHeader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=150, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=150, null=True)),
                ('imageSection', models.FileField(blank=True, default='', null=True, upload_to='blog')),
                ('summary', ckeditor.fields.RichTextField()),
                ('subSection', models.CharField(blank=True, max_length=100, null=True)),
                ('content', ckeditor.fields.RichTextField()),
                ('subSection1', models.CharField(blank=True, max_length=100, null=True)),
                ('content1', ckeditor.fields.RichTextField()),
                ('subSection2', models.CharField(blank=True, max_length=100, null=True)),
                ('content2', ckeditor.fields.RichTextField()),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('articleHead', models.ManyToManyField(blank=True, null=True, to='blogPost.articleheader')),
            ],
        ),
    ]
