# Generated by Django 4.1 on 2022-09-30 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogPost', '0010_articleheader_article'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='title',
            new_name='section',
        ),
        migrations.RenameField(
            model_name='articleheader',
            old_name='name',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='article',
            name='articleHead',
        ),
        migrations.AddField(
            model_name='articleheader',
            name='article',
            field=models.ManyToManyField(blank=True, to='blogPost.article'),
        ),
    ]
