# Generated by Django 4.1 on 2022-10-02 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogPost', '0013_alter_article_content_alter_article_content1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sectionblog',
            name='blogCat',
        ),
        migrations.AddField(
            model_name='titleblog',
            name='sectionBlog',
            field=models.ManyToManyField(blank=True, to='blogPost.sectionblog'),
        ),
    ]
