# Generated by Django 4.1 on 2022-10-02 07:42

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogPost', '0015_alter_sectionblog_content_alter_sectionblog_content1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='titleblog',
            name='intro',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
    ]
